application: pastedown
version: 1
runtime: python
api_version: 1

handlers:
- url: /etc/images
  static_dir: pastedown/views/images
- url: /etc/wmd
  static_dir: pastedown/views/wmd
- url: .*
  script: main.py
